config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    @question = params[:answer]
    if @question.downcase == 'i am going to work'
      @answer_coach = "Great!"
    elsif @question.include?('?')
      @answer_coach = "Silly question, get dressed and go to work!"
    else
      @answer_coach = "I don't care, get dressed and go to work!"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="answer-user">
  <p><%= @question %></p>
  <p>-You</p>
</div>
<div class="answer-coach">
  <p><%= @answer_coach %></p>
  <p>-Your coach</p>
</div>

<%= link_to "Ask a new quesiton", ask_path%>

app/views/questions/ask.html.erb
<p>Ask your coach anything</p>

<form action='/answer' autocomplete="off">
<div class="submit-div">
  <input type="text" name="answer" class="submit-txt">
  <input type="submit" value="Ask" class="submit-btn">
</div>
</form>